# Generated by Django 3.2.12 on 2022-02-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='folloes',
            new_name='follows',
        ),
    ]
